[server]
listen = ["0.0.0.0:8080", "0.0.0.0:8443"]
listen_quic = ["0.0.0.0:8443"]
enable_http3 = true
max_connections = 1000
keep_alive_timeout = 65
request_timeout = 60
send_timeout = 60
client_body_timeout = 60
client_header_timeout = 60
client_max_body_size = 1048576
tcp_nodelay = true
tcp_fastopen = false

[logging]
log_level = "info"
access_log_format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\""

[security]
enable_rate_limiting = true
rate_limit_requests_per_second = 100
rate_limit_burst = 200
max_request_size = 10485760
allowed_methods = ["GET", "POST", "HEAD", "PUT", "DELETE"]

[security.security_headers]
"X-Frame-Options" = "DENY"
"X-Content-Type-Options" = "nosniff"

[compression]
enable_gzip = true
enable_brotli = true
enable_zstd = false
compression_level = 6
min_compress_size = 1024
compress_types = ["text/html", "text/css", "application/javascript", "application/json"]

[upstream]

[virtual_hosts]
[virtual_hosts.default]
server_name = ["localhost"]
document_root = "./www"
index_files = ["index.html"]

[virtual_hosts.default.locations]

[virtual_hosts.default.ssl]
certificate = "./ssl/cert.pem"
private_key = "./ssl/key.pem"
auto_generate_self_signed = true
protocols = ["TLSv1.2", "TLSv1.3"]