name: Dependency Updates

on:
  schedule:
    - cron: '0 10 * * 1'  # Weekly on Mondays at 10 AM
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install cargo-edit
      run: cargo install cargo-edit

    - name: Update dependencies
      run: |
        cargo update
        cargo upgrade --workspace

    - name: Check if there are changes
      id: changes
      run: |
        if git diff --quiet; then
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Run tests
      if: steps.changes.outputs.changes == 'true'
      run: cargo test --all-features

    - name: Create Pull Request
      if: steps.changes.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: weekly dependency updates'
        body: |
          Automated dependency updates.
          
          This PR was automatically created by the dependency update workflow.
          
          Please review the changes and ensure all tests pass before merging.
        branch: chore/dependency-updates
        delete-branch: true
        labels: |
          dependencies
          automated